apiVersion: apps/v1
kind: Deployment
metadata:
  name: insightric-auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insightric-auth-service
  template:
    metadata:
      labels:
        app: insightric-auth-service
  spec:
    containers:
      - name: insightric-auth-service
        image: IMAGE_PLACEHOLDER
        ports:
          - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000