name: CI for Global Infrastructure

on:
    workflow_dispatch:

jobs:
    noop:
        runs-on: ubuntu-latest
        steps:
            - name: No-op
              run: |
                  echo "This workflow intentionally does nothing."
