name: Global Infrastructure and Deployment

permissions:
    contents: read
    id-token: write

on:
    workflow_dispatch:
    push:
        branches: ["dev", "main"]
        paths:
            - "infra/**"
            - "services/**"
            - ".github/workflows/**"
    repository_dispatch:
        types: ["deploy-service"]

jobs:
    # GLOBAL INFRASTRUCTURE & DEPLOYMENT JOB
    infra-deploy:
        runs-on: ubuntu-latest
        if: ${{ github.event_name != 'repository_dispatch' }}

        env:
            AWS_REGION: us-east-1
            ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'prod' || 'staging' }}

        steps:
            - name: Checkout Repository with Submodules
              uses: actions/checkout@v4
              with:
                  submodules: true

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_TERRAFORM }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                  terraform_version: 1.13.4

            - name: Initialize Terraform
              run: |
                  cd infra/terraform
                  terraform init -input=false

            - name: Terraform Apply
              run: |
                  cd infra/terraform
                  terraform apply -auto-approve

            - name: Fetch ECR Repositories
              id: ecr
              run: |
                  cd infra/terraform
                  # Capture raw terraform output (may include terraform-bin prefix)
                  terraform output -json ecr_repositories > ecr_raw.json 2>&1 || true
                  echo "Raw terraform output:"
                  sed -n '1,200p' ecr_raw.json

                  # Extract JSON starting at the first "{" (handles prefix on its own line or same line)
                  awk '/{/{flag=1} flag{print}' ecr_raw.json | sed 's/^[^{]*\(.*\)$/\1/' > ecr.json || true

                  # Ensure jq is available before validating JSON
                  if ! command -v jq >/dev/null 2>&1; then
                    sudo apt-get update && sudo apt-get install -y jq
                  fi

                  echo "Truncated JSON saved as:"
                  echo "BEGIN"
                  cat ecr.json
                  echo "END"
                  # Validate JSON
                  jq -e . ecr.json

            - name: Deploy to Kubernetes
              run: |
                  for file in infra/kubernetes/deployments/*.yaml; do
                    kubectl apply -f "$file"
                  done
                  for file in infra/kubernetes/services/*.yaml; do
                    kubectl apply -f "$file"
                  done

    # LIGHTWEIGHT REDEPLOY JOB
    deploy-service:
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'repository_dispatch' }}

        env:
            AWS_REGION: us-east-1

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  submodules: true

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Update Kubeconfig for EKS
              run: aws eks update-kubeconfig --region $AWS_REGION --name insightric-cluster

            - name: Update Kubernetes Deployment
              env:
                  AWS_REGION: ${{ env.AWS_REGION }}
              run: |
                  SERVICE_NAME="${{ github.event.client_payload.service }}"
                  IMAGE="${{ github.event.client_payload.image }}"

                  echo "Updating $SERVICE_NAME with image $IMAGE"

                  kubectl set image deployment/$SERVICE_NAME \
                      $SERVICE_NAME=$IMAGE --record
            - name: Verify Health Endpoints
              run: |
                  chmod +x scripts/check_health.sh
                  ./scripts/check_health.sh
